### ISSUE TITLE
An Idea

### ISSUE THREAD

**Issue by JB0925** [pallas0/TooGoodScript#30]
https://github.com/pallas0/TooGoodScript/blob/1bea705e30ffbf18f9a050754783cbf01d0b5ca4/app.py#L174

I think this route is fine as is, but one thing you could do if you were looking to shorten it a bit is turn these few lines into its own function:
```
def process_items(items):
    for item in items:
        # do things
```

And then here in the route, you would just call `process_items(items)`.

**Comment by pallas0** [comment]
built and moved to utils
