### ISSUE TITLE
Maybe move this.

### ISSUE THREAD

**Issue by JB0925** [pallas0/TooGoodScript#31]
https://github.com/pallas0/TooGoodScript/blob/1bea705e30ffbf18f9a050754783cbf01d0b5ca4/app.py#L167

I would maybe move this line down to 173. That way it is grouped with the processing of the items. Not a big deal, though.

**Comment by pallas0** [comment]
Gotcha, did that and condensed the process_items function to take in the array of items, so now that section just looks like this:

```bash
items = client.get_items()
process_items(app, db, items, new_subscriber)
````
Way cleaner - thanks!
